package com.example.linkedinclone.controller;

import com.example.linkedinclone.entity.Post;
import com.example.linkedinclone.service.PostService;
import com.example.linkedinclone.dto.PostUpdateRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import java.time.LocalDateTime;
import java.util.*;


@RestController
@RequestMapping("/posts")
public class PostController {

    @Autowired
    private PostService postService;

    @PostMapping
    public ResponseEntity<Map<String, Object>> createPost(@RequestBody Map<String, String> payload) {
        String content = payload.get("content");

        // Create and save the post
        Post newPost = new Post(content);
        Post savedPost = postService.savePost(newPost);

        // Prepare the response
        Map<String, Object> response = new HashMap<>();
        response.put("id", savedPost.getId().toString());  // Use the ID generated by the database
        response.put("name", "Your Name");  // This would come from the logged-in user
        response.put("basicInfo", "Job Title, Location");  // User's basic info
        response.put("avatarUrl", "/images/avatar.jpg");  // User's avatar
        response.put("createdAt", LocalDateTime.now().toString());
        response.put("content", savedPost.getContent());

        return ResponseEntity.ok(response);
    }

    @PutMapping("/{id}")
    public ResponseEntity<Post> updatePost(@PathVariable("id") Long id, @RequestBody PostUpdateRequest updateRequest) {
        Post updatedPost = postService.updatePost(id, updateRequest.getContent());
        if (updatedPost != null) {
            return ResponseEntity.ok(updatedPost);  // Return updated post
        } else {
            return ResponseEntity.notFound().build();  // Handle post not found case
        }

    }

    @GetMapping
    public ResponseEntity<List<Post>> getAllPosts() {
        List<Post> posts = postService.getAllPosts();
        return ResponseEntity.ok(posts);
    }

}
